# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: minimal_custom
  theme_night: minimal_custom
  font: native
  font_size: L

design:
  # background:
    # Choose colors such as from https://html-color-codes.info
    # color: 'navy'
    # gradient_start: '#4bb4e3'
    # gradient_end: '#2b94c3'
    # The gradient angle from 0-360 degrees
    # gradient_angle: 180
    # Text color (true=light, false=dark, or remove for the dynamic theme color).
    # text_color_light: true
  spacing:
    # Customize the section spacing. Order is top, right, bottom, left.
    padding: ["20px", "0", "20px", "0"]
  css_style: ''
  css_class: ''

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The personal and professional website of Davis Daumler.'
    twitter: 'DavisDaumler'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    fixed_to_top: false
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: false
    highlight_active_link: true
    # Shop a call-to-action button in the top right?
    button:
      enable: true
      text: "Download CV"
      url: '/CV/'

# Site footer
footer:
  copyright:
    notice: 'Â© 2024 Davis Daumler. This work is licensed under {license}'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/daumler/davisdaumler/'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: true
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions
extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security
security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
