[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.111.3'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[[redirects]]
  from = "/cv"
  to = "/uploads/Daumler_CV.pdf"
  status = 200
  force = true
[[redirects]]
  from = "/CV"
  to = "/uploads/Daumler_CV.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/Cv"
  to = "/uploads/Daumler_CV.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/cV"
  to = "/uploads/Daumler_CV.pdf"
  status = 301
  force = true